# cache:
#   - '%AppData%\stack'

install:
  - curl -sS -ostack.zip -L https://get.haskellstack.org/stable/windows-i386.zip
  - 7z x stack.zip stack.exe
  - stack setup > nul

build: off

build_script:
  - stack --no-terminal test --no-run-tests --resolver lts-11

test_script:
  - stack --jobs 1 --no-terminal test --resolver lts-11
